In [1]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import gc

# 그래프 기본 테마 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 복잡한 통계 처리를 위한 라이브러리
from scipy import stats
from sklearn.preprocessing import LabelEncoder

In [2]:
# 데이터 불러오기
df707 = pd.read_parquet('open/train/7.마케팅정보/201807_train_마케팅정보.parquet')
df708 = pd.read_parquet('open/train/7.마케팅정보/201808_train_마케팅정보.parquet')
df709 = pd.read_parquet('open/train/7.마케팅정보/201809_train_마케팅정보.parquet')
df710 = pd.read_parquet('open/train/7.마케팅정보/201810_train_마케팅정보.parquet')
df711 = pd.read_parquet('open/train/7.마케팅정보/201811_train_마케팅정보.parquet')
df712 = pd.read_parquet('open/train/7.마케팅정보/201812_train_마케팅정보.parquet')

df707

,기준년월,ID,컨택건수_카드론_TM_B0M,컨택건수_리볼빙_TM_B0M,컨택건수_CA_TM_B0M,컨택건수_이용유도_TM_B0M,컨택건수_신용발급_TM_B0M,컨택건수_부대서비스_TM_B0M,컨택건수_포인트소진_TM_B0M,컨택건수_보험_TM_B0M,...,컨택건수_카드론_당사앱_R6M,컨택건수_CA_당사앱_R6M,컨택건수_리볼빙_당사앱_R6M,컨택건수_이용유도_당사앱_R6M,컨택건수_채권_B0M,컨택건수_FDS_B0M,컨택건수_채권_R6M,컨택건수_FDS_R6M,캠페인접촉건수_R12M,캠페인접촉일수_R12M
0,201807,TRAIN_000000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
1,201807,TRAIN_000001,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15회 이상,10일 이상
2,201807,TRAIN_000002,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
3,201807,TRAIN_000003,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
4,201807,TRAIN_000004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399995,201807,TRAIN_399995,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
399996,201807,TRAIN_399996,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15회 이상,15일 이상
399997,201807,TRAIN_399997,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
399998,201807,TRAIN_399998,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
399999,201807,TRAIN_399999,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상

In [3]:
# 7번 데이터 병합
df7 = pd.concat([df707, df708, df709, df710, df711], ignore_index=True)
df7 = df7.sort_values(by=['ID', '기준년월']).reset_index(drop=True)
df7.tail()

,기준년월,ID,컨택건수_카드론_TM_B0M,컨택건수_리볼빙_TM_B0M,컨택건수_CA_TM_B0M,컨택건수_이용유도_TM_B0M,컨택건수_신용발급_TM_B0M,컨택건수_부대서비스_TM_B0M,컨택건수_포인트소진_TM_B0M,컨택건수_보험_TM_B0M,...,컨택건수_카드론_당사앱_R6M,컨택건수_CA_당사앱_R6M,컨택건수_리볼빙_당사앱_R6M,컨택건수_이용유도_당사앱_R6M,컨택건수_채권_B0M,컨택건수_FDS_B0M,컨택건수_채권_R6M,컨택건수_FDS_R6M,캠페인접촉건수_R12M,캠페인접촉일수_R12M
1999995,201807,TRAIN_399999,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
1999996,201808,TRAIN_399999,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
1999997,201809,TRAIN_399999,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
1999998,201810,TRAIN_399999,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
1999999,201811,TRAIN_399999,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상

In [4]:
pd.set_option('display.float_format', '{:.2f}'.format)  # 출력 포맷 설정 먼저
print(df7.describe(include='all'))

             기준년월            ID  컨택건수_카드론_TM_B0M  컨택건수_리볼빙_TM_B0M  \
count  2000000.00       2000000       2000000.00       2000000.00
unique        NaN        400000              NaN              NaN
top           NaN  TRAIN_000000              NaN              NaN
freq          NaN             5              NaN              NaN
mean    201809.00           NaN             0.17             0.00
std          1.41           NaN             0.70             0.00
min     201807.00           NaN             0.00             0.00
25%     201808.00           NaN             0.00             0.00
50%     201809.00           NaN             0.00             0.00
75%     201810.00           NaN             0.00             0.00
max     201811.00           NaN             4.00             2.00

        컨택건수_CA_TM_B0M  컨택건수_이용유도_TM_B0M  컨택건수_신용발급_TM_B0M  컨택건수_부대서비스_TM_B0M  \
count       2000000.00        2000000.00        2000000.00         2000000.00
unique             NaN               NaN               NaN                NaN
top                NaN               NaN               NaN                NaN
freq               NaN               NaN               NaN                NaN
mean              0.00              0.08              0.00               0.00
std               0.00              0.48              0.00               0.00
min               0.00              0.00              0.00               0.00
25%               0.00              0.00              0.00               0.00
50%               0.00              0.00              0.00               0.00
75%               0.00              0.00              0.00               0.00
max               0.00              3.00              1.00               1.00

        컨택건수_포인트소진_TM_B0M  컨택건수_보험_TM_B0M  ...  컨택건수_카드론_당사앱_R6M  \
count          2000000.00      2000000.00  ...        2000000.00
unique                NaN             NaN  ...               NaN
top                   NaN             NaN  ...               NaN
freq                  NaN             NaN  ...               NaN
mean                 0.00            0.01  ...              0.00
std                  0.00            0.12  ...              0.00
min                  0.00            0.00  ...              0.00
25%                  0.00            0.00  ...              0.00
50%                  0.00            0.00  ...              0.00
75%                  0.00            0.00  ...              0.00
max                  0.00            1.00  ...              0.00

        컨택건수_CA_당사앱_R6M  컨택건수_리볼빙_당사앱_R6M  컨택건수_이용유도_당사앱_R6M  컨택건수_채권_B0M  \
count        2000000.00        2000000.00         2000000.00   2000000.00
unique              NaN               NaN                NaN          NaN
top                 NaN               NaN                NaN          NaN
freq                NaN               NaN                NaN          NaN
mean               0.00              0.00               0.00         0.03
std                0.00              0.00               0.05         0.39
min                0.00              0.00               0.00         0.00
25%                0.00              0.00               0.00         0.00
50%                0.00              0.00               0.00         0.00
75%                0.00              0.00               0.00         0.00
max                0.00              0.00               4.00         8.00

        컨택건수_FDS_B0M  컨택건수_채권_R6M  컨택건수_FDS_R6M  캠페인접촉건수_R12M  캠페인접촉일수_R12M
count     2000000.00   2000000.00    2000000.00       2000000       2000000
unique           NaN          NaN           NaN             6             5
top              NaN          NaN           NaN         1회 이상         1일 이상
freq             NaN          NaN           NaN       1439810       1470962
mean            0.00         0.48          0.00           NaN           NaN
std             0.00         2.21          0.00           NaN           NaN
min             0.00         0.00          0.00           NaN           NaN
25%             0.00         0.00          0.00           NaN           NaN
50%             0.00         0.00          0.00           NaN           NaN
75%             0.00         0.00          0.00           NaN           NaN
max             0.00        33.00          0.00           NaN           NaN

[11 rows x 64 columns]

In [5]:
# segment 데이터 불러오기
segment = pd.read_parquet('open/train/1.회원정보/201807_train_회원정보.parquet')
segment_col = segment[['ID', 'Segment']]

In [6]:
# segment left outer join
df7 = df7.merge(segment_col, on='ID', how='left')
df7.head()

,기준년월,ID,컨택건수_카드론_TM_B0M,컨택건수_리볼빙_TM_B0M,컨택건수_CA_TM_B0M,컨택건수_이용유도_TM_B0M,컨택건수_신용발급_TM_B0M,컨택건수_부대서비스_TM_B0M,컨택건수_포인트소진_TM_B0M,컨택건수_보험_TM_B0M,...,컨택건수_CA_당사앱_R6M,컨택건수_리볼빙_당사앱_R6M,컨택건수_이용유도_당사앱_R6M,컨택건수_채권_B0M,컨택건수_FDS_B0M,컨택건수_채권_R6M,컨택건수_FDS_R6M,캠페인접촉건수_R12M,캠페인접촉일수_R12M,Segment
0,201807,TRAIN_000000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1회 이상,1일 이상,D
1,201808,TRAIN_000000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1회 이상,1일 이상,D
2,201809,TRAIN_000000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1회 이상,1일 이상,D
3,201810,TRAIN_000000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1회 이상,1일 이상,D
4,201811,TRAIN_000000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1회 이상,1일 이상,D

In [7]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 65 columns):
 #   Column             Dtype
---  ------             -----
 0   기준년월               int64
 1   ID                 object
 2   컨택건수_카드론_TM_B0M    int64
 3   컨택건수_리볼빙_TM_B0M    int64
 4   컨택건수_CA_TM_B0M     int64
 5   컨택건수_이용유도_TM_B0M   int64
 6   컨택건수_신용발급_TM_B0M   int64
 7   컨택건수_부대서비스_TM_B0M  int64
 8   컨택건수_포인트소진_TM_B0M  int64
 9   컨택건수_보험_TM_B0M     int64
 10  컨택건수_카드론_LMS_B0M   int64
 11  컨택건수_CA_LMS_B0M    int64
 12  컨택건수_리볼빙_LMS_B0M   int64
 13  컨택건수_이용유도_LMS_B0M  int64
 14  컨택건수_카드론_EM_B0M    int64
 15  컨택건수_CA_EM_B0M     int64
 16  컨택건수_리볼빙_EM_B0M    int64
 17  컨택건수_이용유도_EM_B0M   int64
 18  컨택건수_카드론_청구서_B0M   int64
 19  컨택건수_CA_청구서_B0M    int64
 20  컨택건수_리볼빙_청구서_B0M   int64
 21  컨택건수_이용유도_청구서_B0M  int64
 22  컨택건수_카드론_인터넷_B0M   int64
 23  컨택건수_CA_인터넷_B0M    int64
 24  컨택건수_리볼빙_인터넷_B0M   int64
 25  컨택건수_이용유도_인터넷_B0M  int64
 26  컨택건수_카드론_당사앱_B0M   int64
 27  컨택건수_CA_당사앱_B0M    int64
 28  컨택건수_리볼빙_당사앱_B0M   int64
 29  컨택건수_이용유도_당사앱_B0M  int64
 30  컨택건수_카드론_TM_R6M    int64
 31  컨택건수_CA_TM_R6M     int64
 32  컨택건수_리볼빙_TM_R6M    int64
 33  컨택건수_이용유도_TM_R6M   int64
 34  컨택건수_신용발급_TM_R6M   int64
 35  컨택건수_부대서비스_TM_R6M  int64
 36  컨택건수_포인트소진_TM_R6M  int64
 37  컨택건수_보험_TM_R6M     int64
 38  컨택건수_카드론_LMS_R6M   int64
 39  컨택건수_CA_LMS_R6M    int64
 40  컨택건수_리볼빙_LMS_R6M   int64
 41  컨택건수_이용유도_LMS_R6M  int64
 42  컨택건수_카드론_EM_R6M    int64
 43  컨택건수_CA_EM_R6M     int64
 44  컨택건수_리볼빙_EM_R6M    int64
 45  컨택건수_이용유도_EM_R6M   int64
 46  컨택건수_카드론_청구서_R6M   int64
 47  컨택건수_CA_청구서_R6M    int64
 48  컨택건수_리볼빙_청구서_R6M   int64
 49  컨택건수_이용유도_청구서_R6M  int64
 50  컨택건수_카드론_인터넷_R6M   int64
 51  컨택건수_CA_인터넷_R6M    int64
 52  컨택건수_리볼빙_인터넷_R6M   int64
 53  컨택건수_이용유도_인터넷_R6M  int64
 54  컨택건수_카드론_당사앱_R6M   int64
 55  컨택건수_CA_당사앱_R6M    int64
 56  컨택건수_리볼빙_당사앱_R6M   int64
 57  컨택건수_이용유도_당사앱_R6M  int64
 58  컨택건수_채권_B0M        int64
 59  컨택건수_FDS_B0M       int64
 60  컨택건수_채권_R6M        int64
 61  컨택건수_FDS_R6M       int64
 62  캠페인접촉건수_R12M       object
 63  캠페인접촉일수_R12M       object
 64  Segment            object
dtypes: int64(61), object(4)
memory usage: 991.8+ MB

In [8]:
# 출력할 최대 행 수 제한 없애기 (None으로 설정)
pd.set_option('display.max_rows', None)

# 결측치 개수 출력 (생략 없이 모두 출력)
print(df7.isnull().sum())

기준년월                 0
ID                   0
컨택건수_카드론_TM_B0M      0
컨택건수_리볼빙_TM_B0M      0
컨택건수_CA_TM_B0M       0
컨택건수_이용유도_TM_B0M     0
컨택건수_신용발급_TM_B0M     0
컨택건수_부대서비스_TM_B0M    0
컨택건수_포인트소진_TM_B0M    0
컨택건수_보험_TM_B0M       0
컨택건수_카드론_LMS_B0M     0
컨택건수_CA_LMS_B0M      0
컨택건수_리볼빙_LMS_B0M     0
컨택건수_이용유도_LMS_B0M    0
컨택건수_카드론_EM_B0M      0
컨택건수_CA_EM_B0M       0
컨택건수_리볼빙_EM_B0M      0
컨택건수_이용유도_EM_B0M     0
컨택건수_카드론_청구서_B0M     0
컨택건수_CA_청구서_B0M      0
컨택건수_리볼빙_청구서_B0M     0
컨택건수_이용유도_청구서_B0M    0
컨택건수_카드론_인터넷_B0M     0
컨택건수_CA_인터넷_B0M      0
컨택건수_리볼빙_인터넷_B0M     0
컨택건수_이용유도_인터넷_B0M    0
컨택건수_카드론_당사앱_B0M     0
컨택건수_CA_당사앱_B0M      0
컨택건수_리볼빙_당사앱_B0M     0
컨택건수_이용유도_당사앱_B0M    0
컨택건수_카드론_TM_R6M      0
컨택건수_CA_TM_R6M       0
컨택건수_리볼빙_TM_R6M      0
컨택건수_이용유도_TM_R6M     0
컨택건수_신용발급_TM_R6M     0
컨택건수_부대서비스_TM_R6M    0
컨택건수_포인트소진_TM_R6M    0
컨택건수_보험_TM_R6M       0
컨택건수_카드론_LMS_R6M     0
컨택건수_CA_LMS_R6M      0
컨택건수_리볼빙_LMS_R6M     0
컨택건수_이용유도_LMS_R6M    0
컨택건수_카드론_EM_R6M      0
컨택건수_CA_EM_R6M       0
컨택건수_리볼빙_EM_R6M      0
컨택건수_이용유도_EM_R6M     0
컨택건수_카드론_청구서_R6M     0
컨택건수_CA_청구서_R6M      0
컨택건수_리볼빙_청구서_R6M     0
컨택건수_이용유도_청구서_R6M    0
컨택건수_카드론_인터넷_R6M     0
컨택건수_CA_인터넷_R6M      0
컨택건수_리볼빙_인터넷_R6M     0
컨택건수_이용유도_인터넷_R6M    0
컨택건수_카드론_당사앱_R6M     0
컨택건수_CA_당사앱_R6M      0
컨택건수_리볼빙_당사앱_R6M     0
컨택건수_이용유도_당사앱_R6M    0
컨택건수_채권_B0M          0
컨택건수_FDS_B0M         0
컨택건수_채권_R6M          0
컨택건수_FDS_R6M         0
캠페인접촉건수_R12M         0
캠페인접촉일수_R12M         0
Segment              0
dtype: int64

In [16]:
df_encoded = df.copy()

# 문자형 변수 전체에 대해 Label Encoding 수행 (Segment 포함)
for col in df_encoded.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    # 결측치가 있으면 문자열로 변환해서 인코딩 가능하게 처리
    df_encoded[col] = df_encoded[col].astype(str)
    df_encoded[col] = le.fit_transform(df_encoded[col])

# 숫자형 변수와 인코딩된 문자형 변수 모두 선택
numeric_cols = df_encoded.columns.tolist()

# 상관계수 계산
corr_matrix = df_encoded[numeric_cols].corr()

# Segment_enc는 기존 'Segment' 컬럼이 인코딩된 것이니, 'Segment'를 인코딩해서 새 컬럼으로 만들었다면 그걸 사용하세요.
# 예를 들어, 만약 'Segment_enc'라는 컬럼이 별도로 있다면 그걸 사용
# 여기서는 'Segment' 컬럼이 인코딩된 상태이므로 'Segment' 컬럼으로 대체

segment_corr = corr_matrix['Segment'].sort_values(ascending=False)

print(segment_corr)

Segment_enc          1.00
Segment              1.00
컨택건수_이용유도_TM_R6M     0.17
컨택건수_이용유도_인터넷_R6M    0.07
컨택건수_이용유도_TM_B0M     0.07
컨택건수_신용발급_TM_R6M     0.05
컨택건수_보험_TM_R6M       0.03
컨택건수_카드론_LMS_R6M     0.03
캠페인접촉건수_R12M         0.03
컨택건수_카드론_TM_R6M      0.03
캠페인접촉일수_R12M         0.03
컨택건수_CA_LMS_R6M      0.02
컨택건수_이용유도_인터넷_B0M    0.02
컨택건수_리볼빙_TM_R6M      0.01
컨택건수_카드론_TM_B0M      0.01
컨택건수_부대서비스_TM_R6M    0.01
컨택건수_보험_TM_B0M       0.00
ID                   0.00
컨택건수_리볼빙_TM_B0M      0.00
컨택건수_신용발급_TM_B0M     0.00
컨택건수_부대서비스_TM_B0M    0.00
컨택건수_카드론_청구서_B0M     0.00
기준년월                 0.00
컨택건수_CA_LMS_B0M     -0.00
컨택건수_리볼빙_LMS_R6M    -0.00
컨택건수_이용유도_당사앱_B0M   -0.00
컨택건수_카드론_청구서_R6M    -0.00
컨택건수_CA_TM_R6M      -0.01
컨택건수_카드론_EM_B0M     -0.01
컨택건수_채권_B0M         -0.01
컨택건수_리볼빙_LMS_B0M    -0.01
컨택건수_이용유도_LMS_R6M   -0.01
컨택건수_이용유도_당사앱_R6M   -0.01
컨택건수_CA_청구서_B0M     -0.01
컨택건수_카드론_LMS_B0M    -0.01
컨택건수_이용유도_청구서_R6M   -0.01
컨택건수_카드론_EM_R6M     -0.02
컨택건수_CA_청구서_R6M     -0.02
컨택건수_채권_R6M         -0.02
컨택건수_포인트소진_TM_R6M   -0.03
컨택건수_이용유도_LMS_B0M   -0.04
컨택건수_이용유도_청구서_B0M   -0.07
컨택건수_이용유도_EM_B0M    -0.13
컨택건수_이용유도_EM_R6M    -0.13
컨택건수_CA_TM_B0M        NaN
컨택건수_포인트소진_TM_B0M     NaN
컨택건수_CA_EM_B0M        NaN
컨택건수_리볼빙_EM_B0M       NaN
컨택건수_리볼빙_청구서_B0M      NaN
컨택건수_카드론_인터넷_B0M      NaN
컨택건수_CA_인터넷_B0M       NaN
컨택건수_리볼빙_인터넷_B0M      NaN
컨택건수_카드론_당사앱_B0M      NaN
컨택건수_CA_당사앱_B0M       NaN
컨택건수_리볼빙_당사앱_B0M      NaN
컨택건수_CA_EM_R6M        NaN
컨택건수_리볼빙_EM_R6M       NaN
컨택건수_리볼빙_청구서_R6M      NaN
컨택건수_카드론_인터넷_R6M      NaN
컨택건수_CA_인터넷_R6M       NaN
컨택건수_리볼빙_인터넷_R6M      NaN
컨택건수_카드론_당사앱_R6M      NaN
컨택건수_CA_당사앱_R6M       NaN
컨택건수_리볼빙_당사앱_R6M      NaN
컨택건수_FDS_B0M          NaN
컨택건수_FDS_R6M          NaN
Name: Segment, dtype: float64

In [12]:
zero_var_cols = [col for col in df.select_dtypes(include=['int64','float64']).columns if df[col].var() == 0]
print(zero_var_cols)
# 분산 0인 변수는 상관분석에서 제외해야 할 듯; 제대로 된 결과가 나오지 않음ㅠㅠ

['컨택건수_CA_TM_B0M', '컨택건수_포인트소진_TM_B0M', '컨택건수_CA_EM_B0M', '컨택건수_리볼빙_EM_B0M', '컨택건수_리볼빙_청구서_B0M', '컨택건수_카드론_인터넷_B0M', '컨택건수_CA_인터넷_B0M', '컨택건수_리볼빙_인터넷_B0M', '컨택건수_카드론_당사앱_B0M', '컨택건수_CA_당사앱_B0M', '컨택건수_리볼빙_당사앱_B0M', '컨택건수_CA_EM_R6M', '컨택건수_리볼빙_EM_R6M', '컨택건수_리볼빙_청구서_R6M', '컨택건수_카드론_인터넷_R6M', '컨택건수_CA_인터넷_R6M', '컨택건수_리볼빙_인터넷_R6M', '컨택건수_카드론_당사앱_R6M', '컨택건수_CA_당사앱_R6M', '컨택건수_리볼빙_당사앱_R6M', '컨택건수_FDS_B0M', '컨택건수_FDS_R6M']

In [17]:
import pandas as pd

# 예: corr_series 변수에 위 정리된 상관계수 pandas.Series 가 저장되어 있다고 가정
corr_dict = {
    '기준년월': 0.00,
    'ID': 0.00,
    '컨택건수_카드론_TM_B0M': 0.01,
    '컨택건수_리볼빙_TM_B0M': 0.00,
    '컨택건수_CA_TM_B0M': float('nan'),
    '컨택건수_이용유도_TM_B0M': 0.07,
    '컨택건수_신용발급_TM_B0M': 0.00,
    '컨택건수_부대서비스_TM_B0M': 0.00,
    '컨택건수_포인트소진_TM_B0M': float('nan'),
    '컨택건수_보험_TM_B0M': 0.00,
    '컨택건수_카드론_LMS_B0M': -0.01,
    '컨택건수_CA_LMS_B0M': 0.02,
    '컨택건수_리볼빙_LMS_B0M': -0.01,
    '컨택건수_이용유도_LMS_B0M': -0.04,
    '컨택건수_카드론_EM_B0M': -0.01,
    '컨택건수_CA_EM_B0M': float('nan'),
    '컨택건수_리볼빙_EM_B0M': float('nan'),
    '컨택건수_이용유도_EM_B0M': -0.13,
    '컨택건수_카드론_청구서_B0M': 0.00,
    '컨택건수_CA_청구서_B0M': -0.01,
    '컨택건수_리볼빙_청구서_B0M': float('nan'),
    '컨택건수_이용유도_청구서_B0M': -0.07,
    '컨택건수_카드론_인터넷_B0M': float('nan'),
    '컨택건수_CA_인터넷_B0M': float('nan'),
    '컨택건수_리볼빙_인터넷_B0M': float('nan'),
    '컨택건수_이용유도_인터넷_B0M': 0.02,
    '컨택건수_카드론_당사앱_B0M': float('nan'),
    '컨택건수_CA_당사앱_B0M': float('nan'),
    '컨택건수_리볼빙_당사앱_B0M': float('nan'),
    '컨택건수_이용유도_당사앱_B0M': -0.00,
    '컨택건수_카드론_TM_R6M': 0.03,
    '컨택건수_CA_TM_R6M': -0.01,
    '컨택건수_리볼빙_TM_R6M': 0.01,
    '컨택건수_이용유도_TM_R6M': 0.17,
    '컨택건수_신용발급_TM_R6M': 0.05,
    '컨택건수_부대서비스_TM_R6M': 0.01,
    '컨택건수_포인트소진_TM_R6M': -0.03,
    '컨택건수_보험_TM_R6M': 0.03,
    '컨택건수_카드론_LMS_R6M': 0.03,
    '컨택건수_CA_LMS_R6M': 0.02,
    '컨택건수_리볼빙_LMS_R6M': -0.00,
    '컨택건수_이용유도_LMS_R6M': -0.01,
    '컨택건수_카드론_EM_R6M': -0.02,
    '컨택건수_CA_EM_R6M': float('nan'),
    '컨택건수_리볼빙_EM_R6M': float('nan'),
    '컨택건수_이용유도_EM_R6M': -0.13,
    '컨택건수_카드론_청구서_R6M': -0.00,
    '컨택건수_CA_청구서_R6M': -0.02,
    '컨택건수_리볼빙_청구서_R6M': float('nan'),
    '컨택건수_이용유도_청구서_R6M': -0.01,
    '컨택건수_카드론_인터넷_R6M': float('nan'),
    '컨택건수_CA_인터넷_R6M': float('nan'),
    '컨택건수_리볼빙_인터넷_R6M': float('nan'),
    '컨택건수_이용유도_인터넷_R6M': float('nan'),
    '컨택건수_카드론_당사앱_R6M': float('nan'),
    '컨택건수_CA_당사앱_R6M': float('nan'),
    '컨택건수_리볼빙_당사앱_R6M': float('nan'),
    '컨택건수_이용유도_당사앱_R6M': -0.01,
    '컨택건수_채권_B0M': -0.01,
    '컨택건수_FDS_B0M': float('nan'),
    '컨택건수_채권_R6M': -0.02,
    '컨택건수_FDS_R6M': float('nan'),
    '캠페인접촉건수_R12M': 0.03,
    '캠페인접촉일수_R12M': 0.03,
}

corr_series = pd.Series(corr_dict)

# 엑셀로 저장
corr_series.to_excel('segment_correlation.xlsx', header=['Correlation_with_Segment_enc'])